config/routes.rb
Rails.application.routes.draw do
  resources :groups do
    resources :subscriptions
  end
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', confirmations: 'users/confirmations', passwords: 'users/passwords', unlocks: 'users/unlocks', omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, only: [:show]
  resources :comments, only: [:new, :create, :show, :destroy]
  resources :avatars, only: [:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :group
  
  after_create :new_comment_alert_to_grp_users_email

  # ========= START MAILER METHODS ========= 

  # TO USER
  # Alert All Users Of a Specific Group : New comment in discussion
  def new_comment_alert_to_grp_users_email
    group = self.group
    user_who_commented = self.user
    UserMailer.new_comment_alert_to_grp_users_email(group, user_who_commented).deliver_now
  end

  # ========= END MAILER ========= 

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show]

  # def index
  #   @all_comments = Comment.all
  # end
  
  def show
    @id = params[:id]
    @comment = Comment.find(@id)
  end

  def new
    @comment = Comment.new
  end
    

  def create
    @comment = Comment.new(content: params['content'], user: current_user,  group_id: params['group_id'].to_i)
    if @comment.save
      redirect_to group_path(@comment.group_id), flash: { success:'Your comment has been posted successfully !' }
    else
      redirect_back(fallback_location: root_path)
      @error = @comment.errors.full_messages
      
    end
  end 

  # def edit
  #   @comment = Comment.find(comment_id)
  # end

  # def update
  #   @comment = Comment.find(params[:id])
  #   if @comment.update(content: params['content'], user: User.find_by(first_name: params['first_name'], gossip_id: params['gossip_id']))
  #     redirect_to @comment
  #   else
  #     @error = @comment.errors.full_messages
  #     render :edit
  #   end
  # end
 

  def destroy
    @comment = Group.find(params[:id])
    @comment.destroy
    redirect_to group_path(@comment.group_id), flash: { info:'Your comment has been deleted successfully !' }
  end

 

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.erb
<div class="container">
						<div class="row">
							<div class="col-md-12">
								<div class="contenu-tabs-ilh">
									<div class="replies-list">


<%if @group.comments.empty?%>
<p>No comment yet.</p>
<% end %>

                  <% @group.comments.each_with_index do |comment, index| %>
										<!--- item reply -->
										<div class="reply-ilh">
											<div>
												<div class="photo-ilh">
													<%= image_tag comment.user.avatar, class:"img-fluid photo-ilh", style:"width:50px;height:50px"  %>
												</div>
											</div>	
											<div class="comment-ilh">
												<div class="heading-content">
													<span><%= comment.user.first_name %> <%= comment.user.last_name %></span>
													<span>Posted at <%=comment.created_at%></span>
												</div>
												<div class="body-comment-ilh">
													<%= comment.content %>
												</div>

											</div>
										</div>
										<!-- end reply -->
                  <%end%>

									</div>
                  <% if user_signed_in? %>
									<%= render "comments/form" %>
                <%end%>

								</div>
							</div>
						</div>
					</div>


​

app/views/comments/_form.html.erb
<div class="reply-form-ilh">
  <div class="form-table-ilh-reply">
    <div>
      <div class="photo-user-ilh">
        <%= image_tag current_user.avatar, class:"img-fluid",style:"width:80px;height:80px;" unless current_user.avatar.nil? %>
      </div>
    </div>
    <div>
      <%= form_tag(comments_path, method: 'post', class: 'form-group add-reply-form-ilh') do %>
        <div class="input-group">
          <%= hidden_field_tag(:group_id, @group.id) %>
          <%= text_area_tag 'content' %>
        </div>
        <div class="input-group">
          <%= submit_tag "Post", class:'btn float-right' %>
        </div>
       <% end %>
    </div>
  </div>
</div>