config/routes.rb
Rails.application.routes.draw do
  resources :groups do
    resources :subscriptions
  end
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', confirmations: 'users/confirmations', passwords: 'users/passwords', unlocks: 'users/unlocks', omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, only: [:show]
  resources :comments, only: [:new, :create, :show, :destroy]
  resources :avatars, only: [:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :subscriptions, dependent: :delete_all
  has_many :users, through: :subscriptions
  has_many :comments, dependent: :delete_all
  # after_create :create_group_to_admin_email
  # after_create :user_create_group_to_grp_admin_email
  geocoded_by :city, latitude: :latitude, longitude: :longitude
  after_validation :geocode, if: ->(obj){ obj.city.present? and obj.city_changed? }

  validates :max_attendees, presence: true
  validates :title, presence: true, length: { in: 2..130 }
  validates :meeting_point, presence: true
  validates :city, presence: true
  validates :description, presence: true, length: { in: 6..500 }
  validates :starting_date, presence: true
  validates :work_period, presence: true
  after_initialize :add_default_values 
  scope :find_by_tab, -> (language) {where('lower(udemy_course_title) LIKE ?', "%#{language.downcase}%").order(created_at: :desc)}
  # ========= START MAILER METHODS ========= 

  # TO ADMIN
  # Alert Admin : Group is created by someone
  def create_group_to_admin_email
    admin = User.find_by(is_admin?: true)
    AdminMailer.create_group_to_admin_email(admin).deliver_now
  end
  
  # TO USER
  # Thanks creator a the new group
  def user_create_group_to_grp_admin_email(group)
    group = params[:id]
    grp_admin = group.user
    UserMailer.user_create_group_to_grp_admin_email(grp_admin).deliver_now
  end
  # ========= END MAILER ========= 
  def self.search(search_query, city_query) 
    if city_query.present?
      groups_found = Group.near(city_query)
    else
     groups_found = Group.all
    end
    if search_query.present?
      groups_found = groups_found.select {|group| group["udemy_course_title"].downcase.include?(search_query.downcase) }
    end
    groups_found
  end

  private

  def add_default_values
    self.max_attendees ||= rand(2..15)
    self.title ||= "My group to learn #{self.udemy_course_title}"
    self.meeting_point ||= "On the internet"
    self.city ||= "Wherever you want"
    self.description ||= "We will learn #{self.udemy_course_title}"
    self.work_period ||= "All days long"
    self.starting_date ||= DateTime.now
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :new, :edit, :update, :destroy]
  before_action :is_group_admin?, only: [:edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @search_query = params[:search]
    @city_query = params[:city]
    @groups = Group.all
    @groups_found = Group.search(@search_query, @city_query)
  end

  # GET /groups/1.json
  def show
    udemy = Udemy.new
    @group = Group.find_by(id:params[:id])
    @user = current_user
    @user_sub = Subscription.where(user:@user,group_id:@group.id).exists?
    @group_subs = Subscription.where(group_id:params[:id])
    @udemy_course = udemy.course_details(@group.udemy_course_id)
  end

  # GET /groups/new
  def new
    @group = Group.new
    udemy = Udemy.new

    @search_query = params[:search]
    @courses = udemy.courses_list(params[:search])
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find_by(id:params[:id])
    udemy = Udemy.new
    @udemy_course = udemy.course_details(@group.udemy_course_id)
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(udemy_course_title: params[:udemy_course_title], udemy_course_id: params[:udemy_course_id], udemy_url_img: params[:udemy_url_img], user: current_user)

    respond_to do |format|

      if @group.save
        Subscription.create(user:@group.user,group_id:@group.id)
        format.html { redirect_to edit_group_path(@group), flash: { info:'Good choice mate :) !' }}
        format.json { render :show, status: :created, location: @group }
      else
        puts @group.errors.full_messages
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    
    respond_to do |format|
      
      if @group.update(group_params)
        format.html { redirect_to @group, flash: { success:'Your group was successfully created ! Enjoy !' }}
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_path, flash: { success:'Group was successfully destroyed.' }}
      format.json { head :no_content }
    end
  end
 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:title, :description, :udemy_course_title, :udemy_course_id, :udemy_url_img, :starting_date, :max_attendees, :meeting_point, :remote, :work_period, :city)
    end

    def is_group_admin?
      if current_user == @group.user
        return true 
      else 
        # redirect_to groups_path, alert: "You are not admin of this group"
        redirect_to groups_path, flash: { info:'You are not admin of this group' }
      end
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_last_groups.html.erb
<div class="container-fluid pb-5">
  
  <!-- TITLE SECTION -->
  <div class="container pt-5 text-left">
    <h2 class="pt-3">Lasts groups</h2>
    <p class="sub-section">Find your best group to learn</p>
  </div>
  <!-- END TITLE SECTION -->

  <!-- CARDS -->
  <!-- <div class="container card-deck mx-auto row pb-5 pt-5"> -->
<div class="container pb-5 reverse.pt-5">
  <div class="row">
    <% @groups.sort_by(&:created_at).reverse.take(4).each do |group| %>
    <% @group_subs = Subscription.where(group_id:group.id) %>
      <div class="col-sm-6 col-md-4 col-lg-3">
        <div class="card card-shadow mt-4">
            <%= image_tag group.udemy_url_img, class:"card-img-top img-fluid p-2" unless group.udemy_url_img.nil?  %>
            <div class="card-block">
                <h4 class="card-title"><%= link_to "#{group.title}", group %></h4>
                <small class="card-text"><%= group.udemy_course_title  %></small>

                <small><p class="card-text">
                <% unless @group_subs.nil? || group.max_attendees.nil? %>
                  <% if (@group_subs.length > 0) && (@group_subs.length < group.max_attendees) && (group.starting_date <= Time.now) %>   
                    <span class="text-green">Opening to join</span>
                  <% elsif (@group_subs.length > 0) && (@group_subs.length < group.max_attendees) && (group.starting_date >= Time.now) %>   
                    <span class="text-orange">Start at <%= group.starting_date %></span>
                  <% elsif (@group_subs.length > 0) && (@group_subs.length >= group.max_attendees) %>   
                    <span class="text-red">Closed (full)</span>
                  <% end %>
                <%else%>
                    <span class="text-green">Opening to join</span>
                <%end%>
                  

                   - 
                  <%=group.city%>
                </p></small>

                <!--comment-->
                <% if false %>
                <% end %>
                <!--comment-->

                <div class="avatar-zone">
                <% i = 0 %>
                <%unless @group_subs.nil? %>
              
                <% while (i < 5) do %>
                    <span>
                      <%unless @group_subs[i].nil? %>
                      <%= link_to image_tag(@group_subs[i].user.avatar, style:"width:30px; height:30px", class:"rounded-circle mt-2"), user_path(@group_subs[i].user) if @group_subs[i].user.avatar.attached? %>
                      <%end%>
                    </span>
                  <% i += 1 %>
                <% end %>
                <%end%>
                </div>
                <!--comment-->
                <% if false %>
                <% end %>
                <!--comment-->
            </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
</div>

  <!-- CTA -->
  <div class="container text-center">
  <%= link_to 'Create a group', new_group_path, class:"btn btn-primary text-center" %>
  </div>
  <!-- END CTA -->

app/views/groups/_last_groups_home.html.erb
<div class="container-fluid pb-5">
  
  <!-- TITLE SECTION -->
  <div class="container pt-5 mb-5 text-center">
    <h2 class="pt-3">Lasts groups</h2>
    <p class="sub-section">Find your best group to learn</p>
  </div>
  <!-- END TITLE SECTION -->

  <!-- CARDS -->
  <!-- <div class="container card-deck mx-auto row pb-5 pt-5"> -->
<div class="container pb-5 reverse.pt-5">

  <div class="row">

    <% @groups.sort_by(&:created_at).reverse.take(4).each do |group| %>
    <% @group_subs = Subscription.where(group_id:group.id) %>
      <div class="col-lg-3 col-md-4 col-sm-6 col-12">
        <div class="card card-shadow mt-4">
            <%= image_tag group.udemy_url_img, class:"card-img-top img-fluid p-2" unless group.udemy_url_img.nil?  %>
            <div class="card-block">
                <h4 class="card-title"><%= link_to "#{group.title}", group %></h4>
                <small class="card-text"><%= group.udemy_course_title  %></small>
                

                <small><p class="card-text">
                <% unless @group_subs.nil? || group.max_attendees.nil? %>
                  
                  <% if (@group_subs.length > 0) && (@group_subs.length < group.max_attendees) && (group.starting_date <= Time.now) %>   
                    <span class="text-green">Opening to join</span>
                  <% elsif (@group_subs.length > 0) && (@group_subs.length < group.max_attendees) && (group.starting_date >= Time.now) %>   
                    <span class="text-orange">Start at <%= group.starting_date %></span>
                  <% elsif (@group_subs.length > 0) && (@group_subs.length >= group.max_attendees) %>   
                    <span class="text-red">Closed (full)</span>
                  <% end %>
                  
                  <%else%>
                    <span class="text-green">Opening to join</span>
                  <%end%>

                   - 
                  <%=group.city%>
                </p></small>

                <!--comment-->
                <% if false %>
                <% end %>
                <!--comment-->
                
                <div class="avatar-zone">
                <% i = 0 %>
                <%unless @group_subs.nil? %>
              
                <% while (i < 5) do %>
                    <span>
                      <%unless @group_subs[i].nil? %>
                      <%= link_to image_tag(@group_subs[i].user.avatar, style:"width:30px; height:30px", class:"rounded-circle mt-2"), user_path(@group_subs[i].user) if @group_subs[i].user.avatar.attached? %>
                      <%end%>
                    </span>
                  <% i += 1 %>
                <% end %>
                <%end%>
                </div>
                
                <!--comment-->
                <% if false %>
                <% end %>
                <!--comment-->
            </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
</div>

  <!-- CTA -->
  <div class="container text-center">
  <%= link_to 'Find a group', groups_path, class:"btn btn-primary text-center" %>
  </div>
  <!-- END CTA -->

app/views/groups/_php.html.erb
<!-- card -->
<div class="container">
<div class="row">
    <% @php.sort_by(&:created_at).reverse.each do |group| %>
    <% @group_subs = Subscription.where(group_id:group.id) %>
      <div class="col-sm-6 col-md-4 col-lg-3">
        <div class="card card-shadow mt-4">
            <%= image_tag group.udemy_url_img, class:"card-img-top img-fluid p-2" unless group.udemy_url_img.nil?  %>
            <div class="card-block">
                <h4 class="card-title"><%= link_to "#{group.title}", group %></h4>
                <small class="card-text"><%= group.udemy_course_title  %></small>
                <small><p class="card-text">

                  <% if (@group_subs.length == nil?) && (group.starting_date <= Time.now) %>
                    <span class="text-green">Opening to join</span>
                  <% elsif (@group_subs.length == nil?) && (group.starting_date >= Time.now) %>
                    <span class="text-orange">Start a <%= group.starting_date %></span>
                  <% elsif (@group_subs.length > 0) && (@group_subs.length < group.max_attendees) && (group.starting_date <= Time.now) %>
                    <span class="text-green">Opening to join</span>
                  <% elsif (@group_subs.length > 0) && (@group_subs.length < group.max_attendees) && (group.starting_date >= Time.now) %>
                    <span class="text-orange">Start at <%= group.starting_date %></span>
                  <% elsif (@group_subs.length > 0) && (@group_subs.length >= group.max_attendees) %>
                    <span class="text-red">Closed (full)</span>
                  <% end %>

                   -
                  <%=group.city%>
                </p></small>
                <% if false %>
                <% end %>
                <div class="avatar-zone">
                <% i = 0 %>
                <%unless @group_subs.nil? %>

                <% while (i < 5) do %>
                    <span>
                      <%unless @group_subs[i].nil? %>
                      <%= link_to image_tag(@group_subs[i].user.avatar, style:"width:30px; height:30px", class:"rounded-circle mt-2"), user_path(@group_subs[i].user) if @group_subs[i].user.avatar.attached? %>
                      <%end%>
                    </span>
                  <% i += 1 %>
                <% end %>
                <%end%>
                </div>
                <% if false %>
                <% end %>
            </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<!-- card -->

app/views/groups/_popular_tabs.html.erb
<!-- card -->
<div class="container">
<div class="row">
    <% @groups.find_by_tab(locals[:language]).each do |group| %>
    <% @group_subs = Subscription.where(group_id:group.id) %>
      <div class="col-sm-6 col-md-4 col-lg-3">
        <div class="card card-shadow mt-4">
            <%= image_tag group.udemy_url_img, class:"card-img-top img-fluid p-2" unless group.udemy_url_img.nil?  %>
            <div class="card-block">
                <h4 class="card-title"><%= link_to "#{group.title}", group %></h4>
                <small class="card-text"><%= group.udemy_course_title  %></small>
                <small><p class="card-text">

                  <% if (@group_subs.length == nil?) && (group.starting_date <= Time.now) %>
                    <span class="text-green">Opening to join</span>
                  <% elsif (@group_subs.length == nil?) && (group.starting_date >= Time.now) %>
                    <span class="text-orange">Start a <%= group.starting_date %></span>
                  <% elsif (@group_subs.length > 0) && (@group_subs.length < group.max_attendees) && (group.starting_date <= Time.now) %>
                    <span class="text-green">Opening to join</span>
                  <% elsif (@group_subs.length > 0) && (@group_subs.length < group.max_attendees) && (group.starting_date >= Time.now) %>
                    <span class="text-orange">Start at <%= group.starting_date %></span>
                  <% elsif (@group_subs.length > 0) && (@group_subs.length >= group.max_attendees) %>
                    <span class="text-red">Closed (full)</span>
                  <% end %>

                   -
                  <%=group.city%>
                </p></small>
                <% if false %>
                <% end %>
                <div class="avatar-zone">
                <% i = 0 %>
                <%unless @group_subs.nil? %>

                <% while (i < 5) do %>
                    <span>
                      <%unless @group_subs[i].nil? %>
                      <%= link_to image_tag(@group_subs[i].user.avatar, style:"width:30px; height:30px", class:"rounded-circle mt-2"), user_path(@group_subs[i].user) if @group_subs[i].user.avatar.attached? %>
                      <%end%>
                    </span>
                  <% i += 1 %>
                <% end %>
                <%end%>
                </div>
                <% if false %>
                <% end %>
            </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<!-- card -->

app/views/groups/_results_groups.html.erb
<div class="container-fluid pb-5">
  
  <!-- TITLE SECTION -->
  <div class="container pt-5 text-left">
    <h2 class="pt-3"><span style="font-size:1.8rem;">Groups<%unless @city_query.nil? %><% unless @city_query.empty? %> near <span style="color:rgba(62,48,142,1);font-weight:bold;font-size: 2.3rem !important;"><%= @city_query %></span><%end%><%end%><%unless @search_query.nil? %><% unless @search_query.empty? %> to learn <span style="color:rgba(62,48,142,1);font-weight:bold;font-size: 2.3rem !important;"><%= @search_query %></span><%end%><%end%></span></h2>

  </div>
  <!-- END TITLE SECTION -->

  <!-- CARDS -->
  <!-- <div class="container card-deck mx-auto row pb-5 pt-5"> -->
<div class="container reverse.pt-5">
  <div class="row">

    <% if @groups_found.empty? %>
      <%= image_tag "nogroup.png", class:"img-fluid mt-5 mx-auto"%>
    <%end%>
    <% @groups_found.sort_by(&:created_at).reverse.each do |group| %>
    <% @group_subs = Subscription.where(group_id:group.id) %>
      <div class="col-sm-6 col-md-4 col-lg-3">
        <div class="card card-shadow mt-4">
            <%= image_tag group.udemy_url_img, class:"card-img-top img-fluid p-2" unless group.udemy_url_img.nil?  %>
            <div class="card-block">
                <h4 class="card-title"><%= link_to "#{group.title}", group %></h4>
                <small class="card-text"><%= group.udemy_course_title  %></small>
                
                
                <small><p class="card-text">
                <% unless @group_subs.nil? || group.max_attendees.nil? %>

                  <% if (@group_subs.length > 0) && (@group_subs.length < group.max_attendees) && (group.starting_date <= Time.now) %>   
                    <span class="text-green">Opening to join</span>
                  <% elsif (@group_subs.length > 0) && (@group_subs.length < group.max_attendees) && (group.starting_date >= Time.now) %>   
                    <span class="text-orange">Start at <%= group.starting_date %></span>
                  <% elsif (@group_subs.length > 0) && (@group_subs.length >= group.max_attendees) %>   
                    <span class="text-red">Closed (full)</span>
                  <% end %>

                  <%else%>
                    <span class="text-green">Opening to join</span>
                  <%end%>
                  
                   - 
                  <%=group.city%>
                </p></small>

                <!--comment-->
                <% if false %>
                <% end %>
                <!--comment-->

                <div class="avatar-zone">
                <% i = 0 %>
                <%unless @group_subs.nil? %>
              
                <% while (i < 5) do %>
                    <span>
                      <%unless @group_subs[i].nil? %>
                      <%= link_to image_tag(@group_subs[i].user.avatar, style:"width:30px; height:30px", class:"rounded-circle mt-2"), user_path(@group_subs[i].user) if @group_subs[i].user.avatar.attached? %>
                      <%end%>
                    </span>
                  <% i += 1 %>
                <% end %>
                <%end%>
                </div>
                <!--comment-->
                <% if false %>
                <% end %>
                <!--comment-->
            </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
</div>

  <!-- CTA -->
  <div class="container text-center">
  <%= link_to 'Create your own group', new_group_path, class:"btn btn-primary text-center" %>
  </div>
  <!-- END CTA -->

app/views/groups/_udemy_course.html.erb
<div class="container">
						<div class="row">
							<div class="col-md-12">
								<div class="contenu-tabs-ilh">
									<div class="heading-ilh">
										<h3>Learn <%=@group.udemy_course_title%> with an awesome group.</h3>
										<span class="metas-head-ilh">
											<i class="fas fa-euro"></i> <%=@udemy_course['price'].delete "€" unless @udemy_course.nil? %>
										</span>
									</div>
									<div class="body-tab-ilh">
										<h5>Author : <%=@udemy_course['visible_instructors'].first['title'] unless @udemy_course.nil? %></h5>
										<h5 class="mt-3">More about the group :</h5><p><%= @group.description %></p>
										<p class="mt-5"><%= link_to "Get the course", "https://www.udemy.com#{@udemy_course['url']}", class:'btn-custom mt-5 text-decoration-none' unless @udemy_course.nil?%></p>
									</div>
								</div>
							</div>
						</div>
					</div>   

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<%= render "layouts/header_group_index" %>

<% unless @groups_found.length == Group.all.length %><%= render "results_groups" %><%end%>

<%= render "popular_groups" %>

<%= render "last_groups" %>

app/views/groups/show.html.erb
<!--comment--><% if false %>
<p id="notice"><%= notice %></p>
<% end %><!--comment-->

<%= render "layouts/header_group_show" %>

    <section id="course-section-details">
			<div class="container">
				<div class="row">
					<div class="col-lg-9 col-sm-8 col-xs-12">
						<div class="course-details">
							<div class="metas-course">
								<div class="title-course">
									<h2>
									<%= @group.title %>
                <% unless @group_subs.nil? || @group.max_attendees.nil? %>
										<% if (@group_subs.length > 0) && (@group_subs.length < @group.max_attendees) && (@group.starting_date <= Time.now) %>   
											<span class="custom-badge-ilh green">Opening to join</span>
										<% elsif (@group_subs.length > 0) && (@group_subs.length < @group.max_attendees) && (@group.starting_date >= Time.now) %>   
											<span class="custom-badge-ilh yellow">Start at <%= @group.starting_date %></span>
										<% elsif (@group_subs.length > 0) && (@group_subs.length >= @group.max_attendees) %>   
											<span class="custom-badge-ilh red">Closed (full)</span>
										<% end %>
								<%else%>
                    <span class="custom-badge-ilh green">Opening to join</span>
                <%end%>
										
                  <span class="custom-badge-ilh green"><%= @group.work_period %></span>
									</h2>
									<%if current_user == @group.user %><small style="font-size:13px"><%= link_to 'Edit', edit_group_path(@group)%> | <%= link_to 'Delete', group_path(@group), :method => :delete, data: {:confirm => "You sure?" } %></small><%end%>
								</div>
								<div class="metadata">
									<div class="metadata_box_ilh">
										<div>
											<div class="photo">
                        <%= image_tag @group.user.avatar, class:"img-fluid", style:"width:60px;height:60px" %>
											</div>
										</div>
										<div>
											<div class="data_content_ilh">
												<p><strong>Created by <%= @group.user.first_name %> <%= @group.user.last_name %></strong> - <%= @group_subs.count %> / <%= @group.max_attendees %> attendee<%unless @group.max_attendees.nil?%><% if (@group.max_attendees > 1) %>s<%end%><%end%></p>
												<p class="italic_ilh"><%= @group.city %></p>
											</div>
										</div>
									</div>
								</div>
								
								<div class="resume_course_ilh">
									<p>
										<%= @group.description %>
									</p>
								</div>


                <%unless @group.max_attendees.nil?%>
                  <% if (@group_subs.count < @group.max_attendees) || (@user_sub == true) %>
                	<%end%> 
								
									<% if current_user == @group.user %>
									<% elsif @user_sub == true %>
                    <%= link_to "Leave group", {:controller => "subscriptions", :action => 'destroy', :group_id => @group.id}, class: "btn btn-outline-primary", method: :delete %>
                  <% elsif @user_sub == false %>
                    <%= link_to "Join group", group_subscriptions_path(@group.id), class: "btn btn-primary", method: :post %>
                  <%end%>

                <%else%>
                  <span class="btn btn-grey">Complet</span>
                <%end%>
								
							</div>
						</div>
					</div>
					<div class="col-lg-3 col-sm-4 col-xs-12">
  
            <div class="card card-shadow mt-4">
              <%= image_tag @group.udemy_url_img, class:"card-img-top img-fluid p-2" unless @group.udemy_url_img.nil?  %>
              <div class="card-block">
                  <h6 class="text-center"><%= @group.udemy_course_title %><br><small style="line-height:2.5rem !important"><%=@udemy_course['price'] unless @udemy_course.nil? %></small></h6>
                  
                  <div class="text-center mt-3 mb-3">
                  <% course_url = "https://www.udemy.com/course/" + "#{@group.udemy_course_id.to_s}"%>
									<%= link_to "Get the course", course_url, target: "_blank", class:"btn-custom" %>
								</div>               
              </div>
            </div>

          </div>
					</div>


				</div>
			</div>
		</section>


    <section id="tabs-ilh">
			<div class="container mt-5">
				<div class="row">
					<div class="col-md-12">
						<nav class="custom-tab-nav-ilh">
							<div class="nav nav-tabs" id="nav-tab" role="tablist">
								<a class="nav-item nav-link active sky" id="nav-course-tab" data-toggle="tab" href="#nav-course" role="tab" aria-controls="nav-course" aria-selected="true"><i class="fas fa-bookmark"></i>Course</a>
								<a class="nav-item nav-link blue" id="nav-discussion-tab" data-toggle="tab" href="#nav-discussion" role="tab" aria-controls="nav-discussion" aria-selected="false"><i class="fas fa-cocktail"></i>Discussion</a>
								<a class="nav-item nav-link green" id="nav-participant-tab" data-toggle="tab" href="#nav-participant" role="tab" aria-controls="nav-participant" aria-selected="false"><i class="fas fa-user"></i>Attendee<%unless @group.max_attendees.nil?%><% if (@group.max_attendees > 1) %>s<%end%><%end%> (<%= @group_subs.count %>)</a>
							</div>
						</nav>
					</div>
				</div>
			</div>
		</section>


    <section id="content-tabs-ilh">
			
			<div class="tab-content" id="nav-tabContent">
				<div class="tab-pane fade show active" id="nav-course" role="tabpanel" aria-labelledby="nav-course-tab">
					<%= render "udemy_course" %>
				</div>

				<div class="tab-pane fade" id="nav-discussion" role="tabpanel" aria-labelledby="nav-discussion-tab">
					<%= render "comments/comments" %>
				</div>

				<div class="tab-pane fade" id="nav-participant" role="tabpanel" aria-labelledby="nav-participant-tab">
					<%= render "subscriptions/group_subs" %>
				</div>
			</div>
		</section>
    

<section id="sejoindre-ilh">
			<div class="container">	
				<div class="row">

        <!-- TITLE SECTION -->
          <div class="col-md-12 text-center">
            <h2 class="pt-3">Join your group</h2>
            <p class="sub-section">
              La Félicità - Paris<br>
              Parvis Alan Turing
            </p>
          </div>
        <!-- END TITLE SECTION -->

				</div>
			</div>
			<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2626.354627368286!2d2.370604051442904!3d48.83237401039025!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e673c1a7b05e93%3A0x43df410cb9fd7b90!2sLa%20Felicit%C3%A0!5e0!3m2!1sfr!2sfr!4v1584946772893!5m2!1sfr!2sfr" width="100%" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
</section>

<script>
$('#myTab a').on('click', function (e) {
  e.preventDefault()
  $(this).tab('show')
})

</script>