config/routes.rb
Rails.application.routes.draw do
  resources :groups do
    resources :subscriptions
  end
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', confirmations: 'users/confirmations', passwords: 'users/passwords', unlocks: 'users/unlocks', omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, only: [:show]
  resources :comments, only: [:new, :create, :show, :destroy]
  resources :avatars, only: [:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/views/layouts/_flash_messages.html.erb
<% if flash.present? %>
    <div id='flash'>
    <script>
      <% if flash[:success] %>
        var $toastContent = $('<span><%= flash[:success] %></span>');
        toastr.success($toastContent)
      <% end %>
      <% if flash[:notice] %>
        var $toastContent = $('<span><%= flash[:notice] %></span>');
        toastr.success($toastContent)
      <% end %>
      <% if flash[:info] %>
        var $toastContent = $('<span><%= flash[:info] %></span>');
        toastr.info($toastContent)
      <% end %>
      <% if flash[:danger] %>
        var $toastContent = $('<span><%= flash[:danger] %></span>');
        toastr.error($toastContent)
      <% end %>
    </script>
    </div>
  <% end %>

app/views/layouts/_footer.html.erb
<footer>
			<div class="container mt-5">	
				<div class="row justify-content-center">
					<div class="col-md-2 d-sm-none"></div>
					<div class="col-md-2 col-sm-2 col-xs-6">	
						<div class="widget-menu-footer-ilh">
							<h3>Service</h3>
							<ul>
								<li><a href="">About us</a></li>
								<li><a href="">Careers</a></li>
								<li><a href="">feature tour</a></li>
							</ul>
						</div>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-6">
						<div class="widget-menu-footer-ilh">
							<h3>Product</h3>
							<ul>
								<li><a href="">About us</a></li>
								<li><a href="">Careers</a></li>
								<li><a href="">feature tour</a></li>
							</ul>
						</div>
					</div>
					<div class="col-md-2 col-sm-2">
						<div class="widget-menu-footer-ilh">
							<h3>About</h3>
							<ul>
								<li><a href="">About us</a></li>
								<li><a href="">Careers</a></li>
								<li><a href="">feature tour</a></li>
							</ul>
						</div>
					</div>
					<div class="col-md-4 col-sm-6">
						<div class="widget-footer-newsletter float-right">	
							<h3>Newsletter</h3>
							<form class="form-inline newsleter-form-ilh">
							  <div class="form-group">
							    <input type="Email" class="form-control" id="" placeholder="E-mail">
							  </div>
							  <button type="submit" class="btn btn-primary"><i class="fas fa-paper-plane"></i></button>
							</form>
						</div>
					</div>
				</div>
			</div>

			<div class="copyright-full-width">
				<div class="container">	
				<div class="row">
					<div class="col-md-12">
						<div class="copyright">	
							<div>
								<span class="copyright-text">© 2020 peerclub.io</span>
							</div>
							<div>
								<ul>
									<li><a href="">Learn</a></li>
									<li><a href="">Service</a></li>
									<li><a href="">About</a></li>
									<li><a href="">Support</a></li>
								</ul>
							</div>
							<div>
								<ul class="rss">
									<li><a href=""><i class="fab fa-facebook-f"></i></a></li>
									<li><a href=""><i class="fab fa-twitter"></i></a></li>
									<li><a href=""><i class="fab fa-google-plus-g"></i></a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			</div>
		</footer>

app/views/layouts/_header_group_create.html.erb
<div class="container-fluid head mt-5">
  <div class="header-head mx-auto col-s-12 text-center">
  <span class="punchline-head">Create a group</span><br>
    
  </div>
</div>

app/views/layouts/_header_group_index.html.erb
<div class="container-fluid head mt-5">
  <div class="header-head mx-auto col-s-12 text-center">
  <span class="punchline-head">Find a team you love.</span><br>
    
  </div>
</div>
<div class="container text-center searchbar">
  <%= form_tag("", method: "get") do %>
  <%= label_tag(:city, :city, class:"hidden") %>
  <%= text_field_tag(:city, @city_query, placeholder:"Where are you ?", class:"left_field") %>

  <%= label_tag(:search, :search, class:"hidden") %>
  <%= text_field_tag(:search, @search_query,  placeholder:"What do you want to learn ?", class:"right_field") %>
  <%= submit_tag("Rechercher", class:"btn btn-primary") %>
<% end %>


        <!-- <%= form_tag("", method: "get") do %>
        <%= label_tag(:city, :city, class:"hidden") %>
        <%= text_field_tag(:city, @city_query, class:"left_field") %>
        <%= label_tag(:search, :search, class:"hidden") %>
        <%= text_field_tag(:search, @search_query, class:"right_field") %>
        <%= submit_tag("Rechercher", class:"btn btn-primary") %>
    <% end %> -->
  </div>

app/views/layouts/_header_group_show.html.erb
<div class="container-fluid head mt-5">
  <div class="header-head mx-auto col-s-12 text-center">
  <span class="punchline-head">Find a team you love.</span><br>
    
  </div>
</div>

app/views/layouts/_header_user_profile.html.erb
<div class="container-fluid head mt-5">
  <div class="header-head mx-auto col-s-12 text-center">
  <span class="punchline-head">Join a micro-learning community</span><br>
    
  </div>
</div>

app/views/layouts/_navbar.html.erb
<!-- start navbar -->
  <nav class="navbar navbar-shadow navbar-expand-lg navbar-light bg-white fixed-top">
    <div class="container">

      <%= link_to image_tag("logo.png",  style: "max-width: 150px", alt: "logo"), root_path,  class:"navbar-brand" %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item nav-text pr-4">
            <%= link_to "home", root_path, class:"nav-link" %>
            <span class="sr-only">(current)</span>
          </li>
          
 
         <!-- DROPDOWN LOGIN -->
          <% if user_signed_in? %>
          <li class="nav-item nav-btn pr-3">
            <%= link_to "join a group", groups_path, class:"btn btn-outline-primary" %>
            <span class="sr-only">(current)</span>
          </li>

          <li class="nav-item nav-btn pr-3">
            <%= link_to "Create a group", new_group_path, class:"btn btn-primary" %>
            <span class="sr-only">(current)</span>
          </li>

          <li class="nav-item dropdown">
            <!--<a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Profile
            </a>-->
            <%= link_to image_tag(current_user.avatar, style:"width:45px; height:45px", class:"rounded-circle"), user_path(current_user), { :class => 'nav-link dropdown-toggle dropdown-toggle-avatar', :id => 'navbarDropdown', :role => 'button', 'data-toggle' => 'dropdown', 'aria-haspopup' => 'true', 'aria-expanded' => 'false' } if current_user.avatar.attached? %>

            

            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "My account", user_path(current_user) , class:"dropdown-item" %>
              <%= link_to "Edit infos", edit_user_registration_path, class:"dropdown-item"  %>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
            </div>
          </li>
        <% else %>
          <!-- DROPDOWN NOT LOGIN -->
          <li class="nav-item nav-text pr-4">
            <%= link_to "view groups", groups_path, class:"nav-link" %>
            <span class="sr-only">(current)</span>
          </li>

          <li class="nav-item nav-btn pr-3">
            <%= link_to "enroll now", new_user_registration_path, class:"btn btn-primary" %>
            <span class="sr-only">(current)</span>
          </li>

          <li class="nav-item nav-btn">
            <%= link_to "login", new_user_session_path, class:"btn btn-outline-primary" %>
            <span class="sr-only">(current)</span>
          </li>
          <% end %>
          </ul>
      </div>


    </nav>
     
    
  <!-- end navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Peerclub</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'false' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'false' %>
    <%# <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> %>
    <style>
      @import url('https://fonts.googleapis.com/css?family=Roboto&display=swap');
    </style>
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v6.0&appId=213584126656258&autoLogAppEvents=1"></script>
  </head>

  <body>
    <!-- facebook -->
  <script>
    window.fbAsyncInit = function() {
      FB.init({
        appId      : '{213584126656258}',
        cookie     : true,
        xfbml      : true,
        version    : '{v6.0}'
      });

      FB.AppEvents.logPageView();

    };

    (function(d, s, id){
       var js, fjs = d.getElementsByTagName(s)[0];
       if (d.getElementById(id)) {return;}
       js = d.createElement(s); js.id = id;
       js.src = "https://connect.facebook.net/en_US/sdk.js";
       fjs.parentNode.insertBefore(js, fjs);
     }(document, 'script', 'facebook-jssdk'));
  </script>

   <!--comment-->
  <% if false %>
       <% flash.each do |type, msg| %>
        <div class="alert alert-danger">
          <%= msg %>
        </div>
        <% end %>

 <% end %>
<!--comment-->
  <%= render :partial => 'layouts/flash_messages', :flash => flash %>

  <%= render "layouts/navbar" %>


  <%= yield %>

  <%= render "layouts/footer" %>

  <script src="https://kit.fontawesome.com/b1724147a0.js" crossorigin="anonymous"></script>

</body>

</html>